---
- name: ensure basic packages are installed
  apt: 
    pkg: "{{ item }}"
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - vim 
    - htop 
    - nmap 
    - less 
    - mtr 
    - w3m
    - ssh 
    - telnet
